[supervisord]
nodaemon=true
user=root

[program:mongod]
command=/usr/bin/mongod --bind_ip 0.0.0.0
autorestart=true

[program:webapp]
command=/usr/bin/python3 /opt/app/server.py
autorestart=true

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
