[supervisord]
nodaemon=true
user=root

[program:named]
command=/usr/sbin/named -g -c /etc/bind/named.conf
autorestart=true

[program:dnsmasq]
; -d = no daemon; pot fallar si eth1 encara no existeix a l'arrencada -> autorestart
command=/usr/sbin/dnsmasq -d --conf-file=/etc/dnsmasq.d/oops.conf
autorestart=true
startretries=10

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
