include /opt/symas/etc/openldap/schema/core.schema
include /opt/symas/etc/openldap/schema/cosine.schema
include /opt/symas/etc/openldap/schema/inetorgperson.schema
include /opt/symas/etc/openldap/schema/nis.schema

modulepath /opt/symas/lib/openldap
moduleload back_mdb.so

database mdb
suffix "dc=nexora,dc=lab"
rootdn "cn=Manager,dc=nexora,dc=lab"
rootpw admin123
directory /var/lib/ldap
maxsize 1073741824

# VULNERABILIDAD: lectura anonima de TODO, incluido userPassword
access to *
    by * read
