[supervisord]
nodaemon=true
user=root

[program:postgres]
command=/bin/bash -c 'PGBIN=$(ls -d /usr/lib/postgresql/*/bin | head -1); exec su postgres -c "$PGBIN/postgres -D /var/lib/postgresql/data"'
autorestart=true

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
